CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

--CREATE TABLE IF NOT EXISTS locations (
--  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--  lat FLOAT8 NOT NULL,
--  lon FLOAT8 NOT NULL,
--  CONSTRAINT pk_location PRIMARY KEY (id)
--);

--CREATE TABLE IF NOT EXISTS events (
--  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--  annotation VARCHAR NOT NULL,
--  category_id BIGINT NOT NULL,
--  confirmedRequests BIGINT,
--  created_on TIMESTAMP NOT NULL,
--  description VARCHAR NOT NULL,
--  event_date TIMESTAMP NOT NULL,
--  initiator_id BIGINT NOT NULL,
--  location_id BIGINT NOT NULL,
--  paid BOOLEAN NOT NULL,
--  participant_limit INT,
--  published_on TIMESTAMP,
--  request_moderation BOOLEAN NOT NULL,
--  state VARCHAR(20) NOT NULL,
--  title VARCHAR(120) NOT NULL,
--  CONSTRAINT pk_event PRIMARY KEY (id),
--  CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id),
--  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator_id) REFERENCES users(id),
--  CONSTRAINT fk_events_to_locations FOREIGN KEY(location_id) REFERENCES locations(id)
--);